# Install Filebeat Playbook

- name: Install curl
  apt:
    name: curl
    state: present

- name: Get filebeat base file
  command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

- name: Install filebeat from base file
  command: dpkg -i filebeat-7.6.1-amd64.deb

- name: Copy config file over
  copy:
    src: filebeat-config.yml
    dest: /etc/filebeat/filebeat.yml

- name: Create elastic user
  user:
    name: elastic
    #changeme
    password: $6$/GRhSN.59ZffBZlg$nNMNn.rnndE0dSzxJfhypMVemsr4NWH14LG3VxveDFoZXPPPY9aAsqzjWPV6tx0ueSR9xVtwakXVMRlgtuRXY/
    group: adm

- name: Enable and configure the system module
  command: filebeat modules enable system

- name: Run filebeat setup
  command: filebeat setup

- name: Start filebeat
  command: service filebeat start

